-- AI Companion minimal schema (no auth.uid usage)
-- Requires pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Core chat table
CREATE TABLE IF NOT EXISTS ai_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user','assistant','system')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- simple foreign-key like check without RLS dependency
  CONSTRAINT fk_user_exists CHECK (EXISTS (SELECT 1 FROM users u WHERE u.id = user_id))
);

-- Memories table with vector embeddings
CREATE TABLE IF NOT EXISTS ai_memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  memory_kind TEXT NOT NULL CHECK (memory_kind IN ('like','dislike','hobby','movie','song','trait','life_update','generic')),
  content TEXT NOT NULL,
  embedding VECTOR(1536), -- adjust to chosen embedding size
  importance SMALLINT DEFAULT 1 CHECK (importance BETWEEN 1 AND 5),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_user_exists_mem CHECK (EXISTS (SELECT 1 FROM users u WHERE u.id = user_id))
);

-- Optional IVFFLAT index for similarity search (can be added later when data grows)
-- CREATE INDEX IF NOT EXISTS ai_memories_embedding_ivfflat ON ai_memories USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- Suggestions table to track matchmaking nudges
CREATE TABLE IF NOT EXISTS ai_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user UUID NOT NULL,
  to_user UUID NOT NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'proposed' CHECK (status IN ('proposed','accepted','rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_from_user_exists CHECK (EXISTS (SELECT 1 FROM users u WHERE u.id = from_user)),
  CONSTRAINT fk_to_user_exists CHECK (EXISTS (SELECT 1 FROM users u WHERE u.id = to_user))
);

-- Lightweight helper function to insert memory safely (server-side use)
CREATE OR REPLACE FUNCTION ai_insert_memory(
  p_user_id UUID,
  p_content TEXT,
  p_kind TEXT DEFAULT 'generic',
  p_embedding VECTOR DEFAULT NULL,
  p_importance SMALLINT DEFAULT 1
) RETURNS BIGINT AS $$
DECLARE new_id BIGINT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM users u WHERE u.id = p_user_id) THEN
    RAISE EXCEPTION 'user not found';
  END IF;
  INSERT INTO ai_memories(user_id, content, memory_kind, embedding, importance)
  VALUES (p_user_id, p_content, p_kind, p_embedding, p_importance)
  RETURNING id INTO new_id;
  RETURN new_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Restrict function to service role only (server usage)
REVOKE ALL ON FUNCTION ai_insert_memory(UUID, TEXT, TEXT, VECTOR, SMALLINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ai_insert_memory(UUID, TEXT, TEXT, VECTOR, SMALLINT) TO service_role;